//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Datos.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using WebApp.Dominio.Entidades;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
            : base("name=DatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alim> Alim { get; set; }
        public virtual DbSet<Alim_Fuente> Alim_Fuente { get; set; }
        public virtual DbSet<Alim_Grp> Alim_Grp { get; set; }
        public virtual DbSet<DesCant> DesCant { get; set; }
        public virtual DbSet<Desecho> Desecho { get; set; }
        public virtual DbSet<FactConv> FactConv { get; set; }
        public virtual DbSet<FamRec> FamRec { get; set; }
        public virtual DbSet<Nt_Cant> Nt_Cant { get; set; }
        public virtual DbSet<Nt_Fuente> Nt_Fuente { get; set; }
        public virtual DbSet<Nt_Func> Nt_Func { get; set; }
        public virtual DbSet<Nt_Grp> Nt_Grp { get; set; }
        public virtual DbSet<Nt_Grp_Cant> Nt_Grp_Cant { get; set; }
        public virtual DbSet<Nutriente> Nutriente { get; set; }
        public virtual DbSet<Receta> Receta { get; set; }
        public virtual DbSet<RecProd> RecProd { get; set; }
        public virtual DbSet<Rend> Rend { get; set; }
        public virtual DbSet<RendCant> RendCant { get; set; }
        public virtual DbSet<UniMed> UniMed { get; set; }
        public virtual DbSet<Medida> Medida { get; set; }
        public virtual DbSet<Log4net> Log4net { get; set; }
        public virtual DbSet<LoginAttempts> LoginAttempts { get; set; }
        public virtual DbSet<Password> Password { get; set; }
        public virtual DbSet<PermisosUsuario> PermisosUsuario { get; set; }
        public virtual DbSet<RolUsuario> RolUsuario { get; set; }
        public virtual DbSet<UserPasswords> UserPasswords { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Imagenes> Imagenes { get; set; }
        public virtual DbSet<UserPhotos> UserPhotos { get; set; }
    
    }
}
