//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Aplicacion.Resx {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Aplicacion.Resx.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo.
        /// </summary>
        public static string Alim_FuenteCod {
            get {
                return ResourceManager.GetString("Alim_FuenteCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Alim_FuenteId {
            get {
                return ResourceManager.GetString("Alim_FuenteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Alim_FuenteNombre {
            get {
                return ResourceManager.GetString("Alim_FuenteNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo.
        /// </summary>
        public static string Alim_GrpCod {
            get {
                return ResourceManager.GetString("Alim_GrpCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Alim_GrpId {
            get {
                return ResourceManager.GetString("Alim_GrpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Alim_GrpNombre {
            get {
                return ResourceManager.GetString("Alim_GrpNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conversion Inyectado.
        /// </summary>
        public static string AlimConversionInyectado {
            get {
                return ResourceManager.GetString("AlimConversionInyectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a esAlimento.
        /// </summary>
        public static string AlimesAlimento {
            get {
                return ResourceManager.GetString("AlimesAlimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor Conversion.
        /// </summary>
        public static string AlimFactorConversion {
            get {
                return ResourceManager.GetString("AlimFactorConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor Descuento.
        /// </summary>
        public static string AlimFactorDescuento {
            get {
                return ResourceManager.GetString("AlimFactorDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor Rendimiento.
        /// </summary>
        public static string AlimFactorRendimiento {
            get {
                return ResourceManager.GetString("AlimFactorRendimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Registro.
        /// </summary>
        public static string AlimFechaRegistro {
            get {
                return ResourceManager.GetString("AlimFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fraccionado.
        /// </summary>
        public static string AlimFraccionado {
            get {
                return ResourceManager.GetString("AlimFraccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string AlimId {
            get {
                return ResourceManager.GetString("AlimId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuente Alimenticia.
        /// </summary>
        public static string AlimIdAlimFte {
            get {
                return ResourceManager.GetString("AlimIdAlimFte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo Alimenticio.
        /// </summary>
        public static string AlimIdAlimGrp {
            get {
                return ResourceManager.GetString("AlimIdAlimGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string AlimIdEstado {
            get {
                return ResourceManager.GetString("AlimIdEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad de Medida.
        /// </summary>
        public static string AlimIdUniMed {
            get {
                return ResourceManager.GetString("AlimIdUniMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactivo.
        /// </summary>
        public static string AlimInactivo {
            get {
                return ResourceManager.GetString("AlimInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Abreviado.
        /// </summary>
        public static string AlimNomAbreviado {
            get {
                return ResourceManager.GetString("AlimNomAbreviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string AlimNombre {
            get {
                return ResourceManager.GetString("AlimNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Cientifico.
        /// </summary>
        public static string AlimNomCientifico {
            get {
                return ResourceManager.GetString("AlimNomCientifico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medida Base.
        /// </summary>
        public static string AlimNT_MedidaBase {
            get {
                return ResourceManager.GetString("AlimNT_MedidaBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string DesCantCantidad {
            get {
                return ResourceManager.GetString("DesCantCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Registro.
        /// </summary>
        public static string DesCantFechaRegistro {
            get {
                return ResourceManager.GetString("DesCantFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string DesCantId {
            get {
                return ResourceManager.GetString("DesCantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alimento.
        /// </summary>
        public static string DesCantIdAlim {
            get {
                return ResourceManager.GetString("DesCantIdAlim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desecho.
        /// </summary>
        public static string DesCantIdDes {
            get {
                return ResourceManager.GetString("DesCantIdDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string DesechoId {
            get {
                return ResourceManager.GetString("DesechoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string DesechoNombre {
            get {
                return ResourceManager.GetString("DesechoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Without Repository.
        /// </summary>
        public static string exception_WithoutRepository {
            get {
                return ResourceManager.GetString("exception_WithoutRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor.
        /// </summary>
        public static string FactConvFactor {
            get {
                return ResourceManager.GetString("FactConvFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Registro.
        /// </summary>
        public static string FactConvFechaRegistro {
            get {
                return ResourceManager.GetString("FactConvFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string FactConvId {
            get {
                return ResourceManager.GetString("FactConvId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alimento.
        /// </summary>
        public static string FactConvIdAlim {
            get {
                return ResourceManager.GetString("FactConvIdAlim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medida.
        /// </summary>
        public static string FactConvIdMed {
            get {
                return ResourceManager.GetString("FactConvIdMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base.
        /// </summary>
        public static string FamRecBase {
            get {
                return ResourceManager.GetString("FamRecBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        public static string FamRecDescripcion {
            get {
                return ResourceManager.GetString("FamRecDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Registro.
        /// </summary>
        public static string FamRecFechaRegistro {
            get {
                return ResourceManager.GetString("FamRecFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string FamRecId {
            get {
                return ResourceManager.GetString("FamRecId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string FamRecNombre {
            get {
                return ResourceManager.GetString("FamRecNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string ImagenesId {
            get {
                return ResourceManager.GetString("ImagenesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen.
        /// </summary>
        public static string ImagenesImagen {
            get {
                return ResourceManager.GetString("ImagenesImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre archivo.
        /// </summary>
        public static string ImagenesNomArchivo {
            get {
                return ResourceManager.GetString("ImagenesNomArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Log4netDate {
            get {
                return ResourceManager.GetString("Log4netDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception.
        /// </summary>
        public static string Log4netException {
            get {
                return ResourceManager.GetString("Log4netException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host.
        /// </summary>
        public static string Log4netHost {
            get {
                return ResourceManager.GetString("Log4netHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Log4netId {
            get {
                return ResourceManager.GetString("Log4netId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Level.
        /// </summary>
        public static string Log4netLevel {
            get {
                return ResourceManager.GetString("Log4netLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logger.
        /// </summary>
        public static string Log4netLogger {
            get {
                return ResourceManager.GetString("Log4netLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string Log4netMessage {
            get {
                return ResourceManager.GetString("Log4netMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thread.
        /// </summary>
        public static string Log4netThread {
            get {
                return ResourceManager.GetString("Log4netThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BrowserType.
        /// </summary>
        public static string LoginAttemptsBrowserType {
            get {
                return ResourceManager.GetString("LoginAttemptsBrowserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha creacion.
        /// </summary>
        public static string LoginAttemptsCreatedDate {
            get {
                return ResourceManager.GetString("LoginAttemptsCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string LoginAttemptsId {
            get {
                return ResourceManager.GetString("LoginAttemptsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdUsuario.
        /// </summary>
        public static string LoginAttemptsIdUsuario {
            get {
                return ResourceManager.GetString("LoginAttemptsIdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IPNumber.
        /// </summary>
        public static string LoginAttemptsIPNumber {
            get {
                return ResourceManager.GetString("LoginAttemptsIPNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string LoginAttemptsPassword {
            get {
                return ResourceManager.GetString("LoginAttemptsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        public static string LoginAttemptsSuccess {
            get {
                return ResourceManager.GetString("LoginAttemptsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string MedidaId {
            get {
                return ResourceManager.GetString("MedidaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string MedidaNombre {
            get {
                return ResourceManager.GetString("MedidaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Estandar.
        /// </summary>
        public static string Nt_CantErrorEstandar {
            get {
                return ResourceManager.GetString("Nt_CantErrorEstandar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Registro.
        /// </summary>
        public static string Nt_CantFechaRegistro {
            get {
                return ResourceManager.GetString("Nt_CantFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Nt_CantId {
            get {
                return ResourceManager.GetString("Nt_CantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alimento.
        /// </summary>
        public static string Nt_CantIdAlim {
            get {
                return ResourceManager.GetString("Nt_CantIdAlim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuente Nutricional.
        /// </summary>
        public static string Nt_CantIdNtFte {
            get {
                return ResourceManager.GetString("Nt_CantIdNtFte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nutriente.
        /// </summary>
        public static string Nt_CantIdNut {
            get {
                return ResourceManager.GetString("Nt_CantIdNut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num Obs.
        /// </summary>
        public static string Nt_CantNumObs {
            get {
                return ResourceManager.GetString("Nt_CantNumObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string Nt_CantValor {
            get {
                return ResourceManager.GetString("Nt_CantValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo.
        /// </summary>
        public static string Nt_FuenteCod {
            get {
                return ResourceManager.GetString("Nt_FuenteCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Nt_FuenteId {
            get {
                return ResourceManager.GetString("Nt_FuenteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nt_FuenteNombre {
            get {
                return ResourceManager.GetString("Nt_FuenteNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        public static string Nt_FuncDescripcion {
            get {
                return ResourceManager.GetString("Nt_FuncDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Nt_FuncId {
            get {
                return ResourceManager.GetString("Nt_FuncId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nt_FuncNombre {
            get {
                return ResourceManager.GetString("Nt_FuncNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        public static string Nt_Grp_CantDescripcion {
            get {
                return ResourceManager.GetString("Nt_Grp_CantDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Nt_Grp_CantId {
            get {
                return ResourceManager.GetString("Nt_Grp_CantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nt_Grp_CantNombre {
            get {
                return ResourceManager.GetString("Nt_Grp_CantNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        public static string Nt_GrpDescripcion {
            get {
                return ResourceManager.GetString("Nt_GrpDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Nt_GrpId {
            get {
                return ResourceManager.GetString("Nt_GrpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nt_GrpIdGrpCantNT.
        /// </summary>
        public static string Nt_GrpIdGrpCantNT {
            get {
                return ResourceManager.GetString("Nt_GrpIdGrpCantNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nt_GrpNombre {
            get {
                return ResourceManager.GetString("Nt_GrpNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo.
        /// </summary>
        public static string NutrienteCodigo {
            get {
                return ResourceManager.GetString("NutrienteCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decimales.
        /// </summary>
        public static string NutrienteDecimales {
            get {
                return ResourceManager.GetString("NutrienteDecimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es Esencial.
        /// </summary>
        public static string NutrienteesEsencial {
            get {
                return ResourceManager.GetString("NutrienteesEsencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string NutrienteId {
            get {
                return ResourceManager.GetString("NutrienteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcion Nutricional.
        /// </summary>
        public static string NutrienteIdFuncNT {
            get {
                return ResourceManager.GetString("NutrienteIdFuncNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo Nutricional.
        /// </summary>
        public static string NutrienteIdGrpNT {
            get {
                return ResourceManager.GetString("NutrienteIdGrpNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad de Medida.
        /// </summary>
        public static string NutrienteIdUniMed {
            get {
                return ResourceManager.GetString("NutrienteIdUniMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string NutrienteNombre {
            get {
                return ResourceManager.GetString("NutrienteNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simbolo.
        /// </summary>
        public static string NutrienteSimbolo {
            get {
                return ResourceManager.GetString("NutrienteSimbolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tags.
        /// </summary>
        public static string NutrienteTag {
            get {
                return ResourceManager.GetString("NutrienteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string PasswordActivo {
            get {
                return ResourceManager.GetString("PasswordActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado por.
        /// </summary>
        public static string PasswordCreatedByUserID {
            get {
                return ResourceManager.GetString("PasswordCreatedByUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Creacion.
        /// </summary>
        public static string PasswordFechaCreacion {
            get {
                return ResourceManager.GetString("PasswordFechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string PasswordId {
            get {
                return ResourceManager.GetString("PasswordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string PasswordPassword1 {
            get {
                return ResourceManager.GetString("PasswordPassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Answer.
        /// </summary>
        public static string PasswordPasswordAnswer {
            get {
                return ResourceManager.GetString("PasswordPasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hash.
        /// </summary>
        public static string PasswordPasswordHash {
            get {
                return ResourceManager.GetString("PasswordPasswordHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question.
        /// </summary>
        public static string PasswordPasswordQuestion {
            get {
                return ResourceManager.GetString("PasswordPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salt.
        /// </summary>
        public static string PasswordPasswordSalt {
            get {
                return ResourceManager.GetString("PasswordPasswordSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado por.
        /// </summary>
        public static string PermisosUsuarioCreatedBy {
            get {
                return ResourceManager.GetString("PermisosUsuarioCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha creacion.
        /// </summary>
        public static string PermisosUsuarioCreatedDate {
            get {
                return ResourceManager.GetString("PermisosUsuarioCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Inicio.
        /// </summary>
        public static string PermisosUsuarioFechaInicio {
            get {
                return ResourceManager.GetString("PermisosUsuarioFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha termino.
        /// </summary>
        public static string PermisosUsuarioFechaTermino {
            get {
                return ResourceManager.GetString("PermisosUsuarioFechaTermino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string PermisosUsuarioId {
            get {
                return ResourceManager.GetString("PermisosUsuarioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdRol.
        /// </summary>
        public static string PermisosUsuarioIdRol {
            get {
                return ResourceManager.GetString("PermisosUsuarioIdRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdUsuario.
        /// </summary>
        public static string PermisosUsuarioIdUsuario {
            get {
                return ResourceManager.GetString("PermisosUsuarioIdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre archivo.
        /// </summary>
        public static string PhotoFileName {
            get {
                return ResourceManager.GetString("PhotoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string PhotoId {
            get {
                return ResourceManager.GetString("PhotoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Photo.
        /// </summary>
        public static string PhotoPhoto1 {
            get {
                return ResourceManager.GetString("PhotoPhoto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias.
        /// </summary>
        public static string RecetaAlias {
            get {
                return ResourceManager.GetString("RecetaAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        public static string RecetaDescripcion {
            get {
                return ResourceManager.GetString("RecetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Registro.
        /// </summary>
        public static string RecetaFechaRegistro {
            get {
                return ResourceManager.GetString("RecetaFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string RecetaId {
            get {
                return ResourceManager.GetString("RecetaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string RecetaIdEstado {
            get {
                return ResourceManager.GetString("RecetaIdEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia Recetas.
        /// </summary>
        public static string RecetaIdFamRec {
            get {
                return ResourceManager.GetString("RecetaIdFamRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdFoto.
        /// </summary>
        public static string RecetaIdFoto {
            get {
                return ResourceManager.GetString("RecetaIdFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Receta Base.
        /// </summary>
        public static string RecetaIdRecetaBase {
            get {
                return ResourceManager.GetString("RecetaIdRecetaBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string RecetaNombre {
            get {
                return ResourceManager.GetString("RecetaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preparacion.
        /// </summary>
        public static string RecetaPreparacion {
            get {
                return ResourceManager.GetString("RecetaPreparacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicacion.
        /// </summary>
        public static string RecetaUbicacion {
            get {
                return ResourceManager.GetString("RecetaUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Registro.
        /// </summary>
        public static string RecProdFechaRegistro {
            get {
                return ResourceManager.GetString("RecProdFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gramos.
        /// </summary>
        public static string RecProdGramos {
            get {
                return ResourceManager.GetString("RecProdGramos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string RecProdId {
            get {
                return ResourceManager.GetString("RecProdId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto.
        /// </summary>
        public static string RecProdIdProducto {
            get {
                return ResourceManager.GetString("RecProdIdProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string RecProdIdProveedor {
            get {
                return ResourceManager.GetString("RecProdIdProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Receta.
        /// </summary>
        public static string RecProdIdReceta {
            get {
                return ResourceManager.GetString("RecProdIdReceta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string RendCantCantidad {
            get {
                return ResourceManager.GetString("RendCantCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Registro.
        /// </summary>
        public static string RendCantFechaRegistro {
            get {
                return ResourceManager.GetString("RendCantFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string RendCantId {
            get {
                return ResourceManager.GetString("RendCantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alimento.
        /// </summary>
        public static string RendCantIdAlim {
            get {
                return ResourceManager.GetString("RendCantIdAlim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rendimiento.
        /// </summary>
        public static string RendCantIdRend {
            get {
                return ResourceManager.GetString("RendCantIdRend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string RendId {
            get {
                return ResourceManager.GetString("RendId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string RendNombre {
            get {
                return ResourceManager.GetString("RendNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string RolUsuarioActivo {
            get {
                return ResourceManager.GetString("RolUsuarioActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado por.
        /// </summary>
        public static string RolUsuarioCreatedBy {
            get {
                return ResourceManager.GetString("RolUsuarioCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha creacion.
        /// </summary>
        public static string RolUsuarioCreatedDate {
            get {
                return ResourceManager.GetString("RolUsuarioCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string RolUsuarioId {
            get {
                return ResourceManager.GetString("RolUsuarioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificado por.
        /// </summary>
        public static string RolUsuarioModifiedBy {
            get {
                return ResourceManager.GetString("RolUsuarioModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha modificacion.
        /// </summary>
        public static string RolUsuarioModifiedDate {
            get {
                return ResourceManager.GetString("RolUsuarioModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string RolUsuarioNombre {
            get {
                return ResourceManager.GetString("RolUsuarioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota.
        /// </summary>
        public static string RolUsuarioNota {
            get {
                return ResourceManager.GetString("RolUsuarioNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CodUMed.
        /// </summary>
        public static string UniMedCodUMed {
            get {
                return ResourceManager.GetString("UniMedCodUMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        public static string UniMedDescripcion {
            get {
                return ResourceManager.GetString("UniMedDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string UniMedId {
            get {
                return ResourceManager.GetString("UniMedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string UniMedNombre {
            get {
                return ResourceManager.GetString("UniMedNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario externo.
        /// </summary>
        public static string UserPasswordsExternalUser {
            get {
                return ResourceManager.GetString("UserPasswordsExternalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string UserPasswordsId {
            get {
                return ResourceManager.GetString("UserPasswordsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdPassword.
        /// </summary>
        public static string UserPasswordsIdPassword {
            get {
                return ResourceManager.GetString("UserPasswordsIdPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdUsuario.
        /// </summary>
        public static string UserPasswordsIdUsuario {
            get {
                return ResourceManager.GetString("UserPasswordsIdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string UserPhotosId {
            get {
                return ResourceManager.GetString("UserPhotosId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdImagen.
        /// </summary>
        public static string UserPhotosIdImagen {
            get {
                return ResourceManager.GetString("UserPhotosIdImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdPhoto.
        /// </summary>
        public static string UserPhotosIdPhoto {
            get {
                return ResourceManager.GetString("UserPhotosIdPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IdUsuario.
        /// </summary>
        public static string UserPhotosIdUsuario {
            get {
                return ResourceManager.GetString("UserPhotosIdUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario.
        /// </summary>
        public static string UsuarioAccountName {
            get {
                return ResourceManager.GetString("UsuarioAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string UsuarioActivo {
            get {
                return ResourceManager.GetString("UsuarioActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado por.
        /// </summary>
        public static string UsuarioCreatedBy {
            get {
                return ResourceManager.GetString("UsuarioCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de creacion.
        /// </summary>
        public static string UsuarioCreatedDate {
            get {
                return ResourceManager.GetString("UsuarioCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Externo.
        /// </summary>
        public static string UsuarioExternalUser {
            get {
                return ResourceManager.GetString("UsuarioExternalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string UsuarioId {
            get {
                return ResourceManager.GetString("UsuarioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string UsuarioLanguageId {
            get {
                return ResourceManager.GetString("UsuarioLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificado por.
        /// </summary>
        public static string UsuarioModifiedBy {
            get {
                return ResourceManager.GetString("UsuarioModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de modificacion.
        /// </summary>
        public static string UsuarioModifiedDate {
            get {
                return ResourceManager.GetString("UsuarioModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fotografia.
        /// </summary>
        public static string UsuarioPhoto {
            get {
                return ResourceManager.GetString("UsuarioPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supervisor.
        /// </summary>
        public static string UsuarioSupervisorUserID {
            get {
                return ResourceManager.GetString("UsuarioSupervisorUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota Personal.
        /// </summary>
        public static string UsuarioUserNote {
            get {
                return ResourceManager.GetString("UsuarioUserNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length exceeded [{1}].
        /// </summary>
        public static string validation_FieldMaxLenght {
            get {
                return ResourceManager.GetString("validation_FieldMaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong range [{1} - {2}].
        /// </summary>
        public static string validation_FieldRange {
            get {
                return ResourceManager.GetString("validation_FieldRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Required.
        /// </summary>
        public static string validation_FieldRequired {
            get {
                return ResourceManager.GetString("validation_FieldRequired", resourceCulture);
            }
        }
    }
}
