//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 31/10/2017 21:25:31
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace WebApp.Dominio.Entidades
{

    /// <summary>
    /// There are no comments for Usp_ProdInfoNutricional_ShowAll in the schema.
    /// </summary>
    public partial class Usp_ProdInfoNutricional    {

        #region Properties
    
        /// <summary>
        /// There are no comments for EsAlimento in the schema.
        /// </summary>
        public virtual int EsAlimento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdProducto in the schema.
        /// </summary>
        public virtual int IdProducto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Producto in the schema.
        /// </summary>
        public virtual string Producto
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FDSRCID in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> FDSRCID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for OrigenAlimento in the schema.
        /// </summary>
        public virtual string OrigenAlimento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FDGRPID in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> FDGRPID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for GrupoAlimento in the schema.
        /// </summary>
        public virtual string GrupoAlimento
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NTID in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> NTID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Nutriente in the schema.
        /// </summary>
        public virtual string Nutriente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NTSYM in the schema.
        /// </summary>
        public virtual string NTSYM
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NTVALUE in the schema.
        /// </summary>
        public virtual global::System.Nullable<decimal> NTVALUE
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NTMedidaBase in the schema.
        /// </summary>
        public virtual global::System.Nullable<decimal> NTMedidaBase
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdUnidadMedida in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> IdUnidadMedida
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UMNutriente in the schema.
        /// </summary>
        public virtual string UMNutriente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NTSRCID in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> NTSRCID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for OrigenNutriente in the schema.
        /// </summary>
        public virtual string OrigenNutriente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdGrpCantNT in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> IdGrpCantNT
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NTClasificacion in the schema.
        /// </summary>
        public virtual string NTClasificacion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdGrpNT in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> IdGrpNT
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TipoNutriente in the schema.
        /// </summary>
        public virtual string TipoNutriente
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for IdFuncNT in the schema.
        /// </summary>
        public virtual global::System.Nullable<int> IdFuncNT
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for NTFuncion in the schema.
        /// </summary>
        public virtual string NTFuncion
        {
            get;
            set;
        }


        #endregion
    
    }

}
