
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

#region

using WebApp.Dominio.Core.Repositories;
using WebApp.Dominio.Entidades;

#endregion

namespace WebApp.Dominio.IRepository
{
    using System;
    using System.Collections.Generic;
    
    public interface ILoginAttemptsRepository : IRepositoryAsync<LoginAttempts> { }
}
