//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Transversales.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Transversal.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The provided string argument must not be empty...
        /// </summary>
        public static string ArgumentMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation Object Type.
        /// </summary>
        public static string BankingValidationResult_ObjectType {
            get {
                return ResourceManager.GetString("BankingValidationResult_ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validation Result Type.
        /// </summary>
        public static string BankingValidationResult_ResultType {
            get {
                return ResourceManager.GetString("BankingValidationResult_ResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not mapped found for type {0} to type {1}.
        /// </summary>
        public static string exception_NotMapFoundForTypeAdapter {
            get {
                return ResourceManager.GetString("exception_NotMapFoundForTypeAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The type is not a fully qualified assembly name.
        /// </summary>
        public static string exception_RegisterTypeMapConfigurationElementInvalidTypeValue {
            get {
                return ResourceManager.GetString("exception_RegisterTypeMapConfigurationElementInvalidTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failure type, expected is RegisterTypesMapConfigurationElement.
        /// </summary>
        public static string exception_RegisterTypesMapConfigurationInvalidType {
            get {
                return ResourceManager.GetString("exception_RegisterTypesMapConfigurationInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro {0} debe estar entre {1} y {2}..
        /// </summary>
        public static string ParameterCheck_Between {
            get {
                return ResourceManager.GetString("ParameterCheck_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro {0} debe estar entre {1} y {2} y no puede ser igual a {3}..
        /// </summary>
        public static string ParameterCheck_BetweenNotEqual {
            get {
                return ResourceManager.GetString("ParameterCheck_BetweenNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ruta de directorio especificada {0} no existe..
        /// </summary>
        public static string ParameterCheck_DirectoryNotExists {
            get {
                return ResourceManager.GetString("ParameterCheck_DirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ruta de archivo especificada {0} no existe..
        /// </summary>
        public static string ParameterCheck_FileNotExists {
            get {
                return ResourceManager.GetString("ParameterCheck_FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro {0} no es una dirección IP4 legal..
        /// </summary>
        public static string ParameterCheck_Ip4Address {
            get {
                return ResourceManager.GetString("ParameterCheck_Ip4Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La ruta de archivo especificada {0} es ilegal..
        /// </summary>
        public static string ParameterCheck_IsFilePath {
            get {
                return ResourceManager.GetString("ParameterCheck_IsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parámetro {0} no coincide con el formato {1}..
        /// </summary>
        public static string ParameterCheck_Match {
            get {
                return ResourceManager.GetString("ParameterCheck_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del parámetro {0} no es válido..
        /// </summary>
        public static string ParameterCheck_Match2 {
            get {
                return ResourceManager.GetString("ParameterCheck_Match2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro {0} no puede ser Guid.Empty.
        /// </summary>
        public static string ParameterCheck_NotEmpty_Guid {
            get {
                return ResourceManager.GetString("ParameterCheck_NotEmpty_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parámetro {0} no puede ser igual a {1}..
        /// </summary>
        public static string ParameterCheck_NotEqual {
            get {
                return ResourceManager.GetString("ParameterCheck_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro {0} debe ser mayor que {1}..
        /// </summary>
        public static string ParameterCheck_NotGreaterThan {
            get {
                return ResourceManager.GetString("ParameterCheck_NotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro {0} debe ser mayor o igual que {1}..
        /// </summary>
        public static string ParameterCheck_NotGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("ParameterCheck_NotGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro {0} debe ser menor que {1}..
        /// </summary>
        public static string ParameterCheck_NotLessThan {
            get {
                return ResourceManager.GetString("ParameterCheck_NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro {0} debe ser menor o igual que {1}..
        /// </summary>
        public static string ParameterCheck_NotLessThanOrEqual {
            get {
                return ResourceManager.GetString("ParameterCheck_NotLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parámetro {0} no puede ser una referencia nula..
        /// </summary>
        public static string ParameterCheck_NotNull {
            get {
                return ResourceManager.GetString("ParameterCheck_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parámetro {0} no puede ser una referencia nula o una colección vacía..
        /// </summary>
        public static string ParameterCheck_NotNullOrEmpty_Collection {
            get {
                return ResourceManager.GetString("ParameterCheck_NotNullOrEmpty_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parámetro {0} no puede ser una referencia nula o una cadena vacía..
        /// </summary>
        public static string ParameterCheck_NotNullOrEmpty_String {
            get {
                return ResourceManager.GetString("ParameterCheck_NotNullOrEmpty_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro {0} no es un puerto válido..
        /// </summary>
        public static string ParameterCheck_Port {
            get {
                return ResourceManager.GetString("ParameterCheck_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud del parámetro {0} debe ser {1}..
        /// </summary>
        public static string ParameterCheck_StringLength {
            get {
                return ResourceManager.GetString("ParameterCheck_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor del parámetro {0} no es una URL legal..
        /// </summary>
        public static string ParameterCheck_Url {
            get {
                return ResourceManager.GetString("ParameterCheck_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clave del parámetro debe tener 8 o 24 de longitud y actualmente es {0}..
        /// </summary>
        public static string Security_DES_KeyLenght {
            get {
                return ResourceManager.GetString("Security_DES_KeyLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parámetro hashType debe ser MD5 o SHA1.
        /// </summary>
        public static string Security_RSA_Sign_HashType {
            get {
                return ResourceManager.GetString("Security_RSA_Sign_HashType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timer Name: {0}.
        /// </summary>
        public static string TestContextWithTimer_BeginTimer {
            get {
                return ResourceManager.GetString("TestContextWithTimer_BeginTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End Time: {0}.
        /// </summary>
        public static string TestContextWithTimer_EndTime {
            get {
                return ResourceManager.GetString("TestContextWithTimer_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Time: {0}.
        /// </summary>
        public static string TestContextWithTimer_StartTime {
            get {
                return ResourceManager.GetString("TestContextWithTimer_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timer Duration: {0}.
        /// </summary>
        public static string TestContextWithTimer_TimerDuration {
            get {
                return ResourceManager.GetString("TestContextWithTimer_TimerDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The constructor {1} selected for type {0} has ref or out parameters. Such parameters are not supported for constructor injection..
        /// </summary>
        public static string TypesAreNotAssignable {
            get {
                return ResourceManager.GetString("TypesAreNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;lt;unknown&amp;gt;.
        /// </summary>
        public static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
    }
}
